[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault_test = "DuBh61ETcQe7dXDAaEPt7fYuLJczfuN3SuSonBdqWp3t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
